//! Embed `library/std` into the `coffee` CLI at compile time.
//!
//! Walks the tree even if it is empty/missing so a parallel Task 1 can land
//! sources after this crate starts building; `cargo:rerun-if-changed` rebuilds.

use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=library");

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let src_root = manifest.join("library/std");
    let embed_dir = out.join("std_embed");
    let _ = fs::remove_dir_all(&embed_dir);
    fs::create_dir_all(&embed_dir).expect("create OUT_DIR/std_embed");

    let mut files: Vec<String> = Vec::new();
    if src_root.is_dir() {
        walk_copy(&src_root, &src_root, &embed_dir, &mut files)
            .expect("copy library/std into OUT_DIR");
    }
    files.sort();

    let mut generated = String::from(
        "// Generated by build.rs — do not edit.\n\
         pub fn embedded_std_files() -> &'static [(&'static str, &'static [u8])] {\n\
             &[\n",
    );
    for rel in &files {
        let escaped = rust_escape(rel);
        generated.push_str(&format!(
            "        (\"{escaped}\", include_bytes!(\"std_embed/{escaped}\")),\n"
        ));
    }
    generated.push_str("    ]\n}\n");

    fs::write(out.join("std_embed.rs"), generated).expect("write std_embed.rs");

    let build_id = hash_compiler_tree(&manifest).expect("hash compiler tree");
    println!("cargo:rustc-env=COFFEE_COMPILER_HASH={build_id}");
}

fn rust_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn walk_copy(
    dir: &Path,
    root: &Path,
    dest_root: &Path,
    files: &mut Vec<String>,
) -> Result<(), String> {
    let entries = fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|e| format!("{}: {e}", dir.display()))?;
        let path = entry.path();
        let ft = entry
            .file_type()
            .map_err(|e| format!("{}: {e}", path.display()))?;
        if ft.is_dir() {
            walk_copy(&path, root, dest_root, files)?;
        } else if ft.is_file() {
            let rel = path
                .strip_prefix(root)
                .map_err(|_| format!("not under {}: {}", root.display(), path.display()))?;
            if rel.components().any(|c| c.as_os_str() == "..") {
                continue;
            }
            let rel_str = rel.to_string_lossy().replace('\\', "/");
            let dest = dest_root.join(rel);
            if let Some(parent) = dest.parent() {
                fs::create_dir_all(parent)
                    .map_err(|e| format!("{}: {e}", parent.display()))?;
            }
            fs::copy(&path, &dest).map_err(|e| format!("copy {}: {e}", path.display()))?;
            files.push(rel_str);
        }
    }
    Ok(())
}

fn hash_compiler_tree(manifest: &Path) -> Result<String, String> {
    let mut files = Vec::new();
    collect_files(manifest, manifest.join("Cargo.toml"), &mut files)?;
    collect_files(manifest, manifest.join("build.rs"), &mut files)?;
    collect_dir(manifest, &manifest.join("src"), &mut files)?;
    collect_dir(manifest, &manifest.join("library"), &mut files)?;
    files.sort_by(|a, b| a.0.cmp(&b.0));
    let mut hasher = Sha256::new();
    for (path, bytes) in &files {
        hasher.update(path.as_bytes());
        hasher.update([0u8]);
        hasher.update((bytes.len() as u64).to_le_bytes());
        hasher.update(bytes);
    }
    Ok(format!("{:x}", hasher.finalize()))
}

fn collect_files(root: &Path, file: PathBuf, out: &mut Vec<(String, Vec<u8>)>) -> Result<(), String> {
    if !file.is_file() {
        return Ok(());
    }
    let rel = file
        .strip_prefix(root)
        .unwrap_or(&file)
        .to_string_lossy()
        .replace('\\', "/");
    let bytes = fs::read(&file).map_err(|e| format!("{}: {e}", file.display()))?;
    out.push((rel, bytes));
    Ok(())
}

fn collect_dir(root: &Path, dir: &Path, out: &mut Vec<(String, Vec<u8>)>) -> Result<(), String> {
    if !dir.is_dir() {
        return Ok(());
    }
    let entries = fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|e| format!("{}: {e}", dir.display()))?;
        let path = entry.path();
        let name = entry.file_name();
        if name == ".git" || name == "target" {
            continue;
        }
        let ft = entry
            .file_type()
            .map_err(|e| format!("{}: {e}", path.display()))?;
        if ft.is_dir() {
            collect_dir(root, &path, out)?;
        } else if ft.is_file() {
            collect_files(root, path, out)?;
        }
    }
    Ok(())
}
